### ISSUE TITLE
CotNet Test

### ISSUE THREAD

**Issue by amirhamidihd** [JDAI-CV/CoTNet#12]
How can I test the CotNet on a single image, 
there is no demo file on your git.

which file should be added to the detectron2 sources for running the demo test?
where should I add the pre-trained model?

**Comment by YehLi** [comment]
You can refer to https://github.com/rwightman/pytorch-image-models for inference.

For detection and segmentation tasks, you can follow the guidance to test a single arbitrary image(https://detectron2.readthedocs.io/en/latest/tutorials/getting_started.html#inference-demo-with-pre-trained-models).
