### ISSUE TITLE
Can the CoTNet50 model be transferred to caffe?

### ISSUE THREAD

**Issue by Single430** [JDAI-CV/CoTNet#13]
RT

**Comment by YehLi** [comment]
You can transfer it to caffe, but you need to write a new layer (the aggregation_zeropad function in aggregation_zeropad.py).

**Comment by Single430** [comment]
> You can transfer it to caffe, but you need to write a new layer (the aggregation_zeropad function in aggregation_zeropad.py).

Thank you, I have indeed encountered a problem at this step now, and I need to reimplement the method in aggregation_zeropad by myself...

**Comment by YehLi** [comment]
You need to implement .cpp and .cu files in caffe. For .cu file, you can refer to the code (forward_kernel, backward_kernel) in aggregation_zeropad.py.

**Comment by Single430** [comment]
> You need to implement .cpp and .cu files in caffe. For .cu file, you can refer to the code (forward_kernel, backward_kernel) in aggregation_zeropad.py.

Thank you very much for your reply. It is also difficult for me to implement cpp. Thank you very much!
