### ISSUE TITLE
About run the script

### ISSUE THREAD

**Issue by 523997931** [JDAI-CV/CoTNet#3]
I try to use the CoTNet 50 to run the train. but when i use the script, it said that the import error about this module:

from .test_time_pool import TestTimePoolHead, apply_test_time_pool

and I saw the dir, I can't find this file

**Comment by zhangjunyi1225054736** [comment]
I also have this error, hao to solve it ?

**Comment by zhang-pan** [comment]
我也有这个错误，在models/layers下没有对应的这个文件

**Comment by YehLi** [comment]
I have uploaded the test_time_pool.py file. The problem can be solved now.
