### ISSUE TITLE
Codes about object detection and instance segmentation

### ISSUE THREAD

**Issue by qiaoqiaowudi** [JDAI-CV/CoTNet#5]
Thank you for your work, is there any plan about releasing the codes of object detection and instance segmentation which has describes in the paper? I want to do some experiments but I cannot find any codes about that.

**Comment by YehLi** [comment]
We will release the code for object detection and instance segmentation soon.

**Comment by jinfagang** [comment]
@YehLi  Does there any timeline on this? Is it based on detectron2 or mmdetection?

**Comment by YehLi** [comment]
The code is available at https://github.com/JDAI-CV/CoTNet-ObjectDetection-InstanceSegmentation.
