### ISSUE TITLE
from cupy_layers.aggregation_zeropad import LocalConvolution

### ISSUE THREAD

**Issue by ZJX-CV** [JDAI-CV/CoTNet#6]
找不到这个包啊兄弟 .... cotnet.py中 请问这个是你们自己写的还是公共的包

**Comment by rrrlifang** [comment]
请问你找到了吗？我也遇到了这个问题

**Comment by BrigittaLindholm** [comment]
25年了，有谁知道这个包是哪里来的吗？

**Comment by BrigittaLindholm** [comment]
为防止后来人还是找不到，我找到了-->https://github.com/JDAI-CV/CoTNet/tree/master/cupy_layers
