### ISSUE TITLE
训练精度提不上去

### ISSUE THREAD

**Issue by ai1361720220000** [JDAI-CV/CoTNet#9]
你好，我将数据集换用自己的一个分类的问题，修改了num_classes
但是在训练前几个epoch，模型就很快达到81%，之后就不变了？
[INFO: 2021-08-06 03:11:28,969] Epoch: 1, top1_acc = 81.50%, top5_acc = 88.03% in 1011
[INFO: 2021-08-06 03:11:50,782] Epoch: 1, top1_acc = 78.34%, top5_acc = 90.80% in 1011
[INFO: 2021-08-06 03:11:54,979] Current checkpoints:
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-1.pth.tar', 0.7833827893175074)

[INFO: 2021-08-06 03:12:06,148] Distributing BatchNorm running means and vars
[INFO: 2021-08-06 03:12:29,904] Epoch: 2, top1_acc = 81.50%, top5_acc = 91.30% in 1011
[INFO: 2021-08-06 03:12:52,995] Epoch: 2, top1_acc = 80.32%, top5_acc = 91.00% in 1011
[INFO: 2021-08-06 03:12:57,295] Current checkpoints:
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-2.pth.tar', 0.8031651829871415)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-1.pth.tar', 0.7833827893175074)

[INFO: 2021-08-06 03:13:07,683] Distributing BatchNorm running means and vars
[INFO: 2021-08-06 03:13:30,486] Epoch: 3, top1_acc = 81.50%, top5_acc = 90.60% in 1011
[INFO: 2021-08-06 03:13:51,824] Epoch: 3, top1_acc = 81.40%, top5_acc = 91.10% in 1011
[INFO: 2021-08-06 03:13:55,495] Current checkpoints:
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-3.pth.tar', 0.8140454995054401)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-2.pth.tar', 0.8031651829871415)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-1.pth.tar', 0.7833827893175074)

[INFO: 2021-08-06 03:14:06,663] Distributing BatchNorm running means and vars
[INFO: 2021-08-06 03:14:28,298] Epoch: 4, top1_acc = 81.50%, top5_acc = 90.90% in 1011
[INFO: 2021-08-06 03:14:50,402] Epoch: 4, top1_acc = 81.50%, top5_acc = 91.00% in 1011
[INFO: 2021-08-06 03:14:54,367] Current checkpoints:
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-4.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-3.pth.tar', 0.8140454995054401)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-2.pth.tar', 0.8031651829871415)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-1.pth.tar', 0.7833827893175074)

[INFO: 2021-08-06 03:15:04,976] Distributing BatchNorm running means and vars
[INFO: 2021-08-06 03:15:28,693] Epoch: 5, top1_acc = 81.50%, top5_acc = 90.60% in 1011
[INFO: 2021-08-06 03:15:50,798] Epoch: 5, top1_acc = 81.50%, top5_acc = 91.00% in 1011
[INFO: 2021-08-06 03:15:54,580] Current checkpoints:
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-4.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-5.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-3.pth.tar', 0.8140454995054401)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-2.pth.tar', 0.8031651829871415)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-1.pth.tar', 0.7833827893175074)

[INFO: 2021-08-06 03:16:05,745] Distributing BatchNorm running means and vars
[INFO: 2021-08-06 03:16:28,279] Epoch: 6, top1_acc = 81.50%, top5_acc = 90.60% in 1011
[INFO: 2021-08-06 03:16:50,315] Epoch: 6, top1_acc = 81.50%, top5_acc = 91.00% in 1011
[INFO: 2021-08-06 03:16:53,875] Current checkpoints:
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-4.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-5.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-6.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-3.pth.tar', 0.8140454995054401)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-2.pth.tar', 0.8031651829871415)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-1.pth.tar', 0.7833827893175074)

[INFO: 2021-08-06 03:17:04,938] Distributing BatchNorm running means and vars
[INFO: 2021-08-06 03:17:25,901] Epoch: 7, top1_acc = 81.50%, top5_acc = 90.60% in 1011
[INFO: 2021-08-06 03:17:47,415] Epoch: 7, top1_acc = 81.50%, top5_acc = 91.00% in 1011
[INFO: 2021-08-06 03:17:51,371] Current checkpoints:
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-4.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-5.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-6.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-7.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-3.pth.tar', 0.8140454995054401)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-2.pth.tar', 0.8031651829871415)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-1.pth.tar', 0.7833827893175074)

[INFO: 2021-08-06 03:18:03,222] Distributing BatchNorm running means and vars
[INFO: 2021-08-06 03:18:25,004] Epoch: 8, top1_acc = 81.50%, top5_acc = 90.60% in 1011
[INFO: 2021-08-06 03:18:45,917] Epoch: 8, top1_acc = 81.50%, top5_acc = 91.00% in 1011
[INFO: 2021-08-06 03:18:49,683] Current checkpoints:
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-4.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-5.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-6.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-7.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-8.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-3.pth.tar', 0.8140454995054401)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-2.pth.tar', 0.8031651829871415)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-1.pth.tar', 0.7833827893175074)

[INFO: 2021-08-06 03:19:00,600] Distributing BatchNorm running means and vars
[INFO: 2021-08-06 03:19:22,594] Epoch: 9, top1_acc = 81.50%, top5_acc = 90.60% in 1011
[INFO: 2021-08-06 03:19:44,611] Epoch: 9, top1_acc = 81.50%, top5_acc = 91.00% in 1011
[INFO: 2021-08-06 03:19:48,289] Current checkpoints:
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-4.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-5.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-6.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-7.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-8.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-9.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-3.pth.tar', 0.8140454995054401)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-2.pth.tar', 0.8031651829871415)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-1.pth.tar', 0.7833827893175074)

[INFO: 2021-08-06 03:19:59,657] Distributing BatchNorm running means and vars
[INFO: 2021-08-06 03:20:21,286] Epoch: 10, top1_acc = 81.50%, top5_acc = 90.60% in 1011
[INFO: 2021-08-06 03:20:42,669] Epoch: 10, top1_acc = 81.50%, top5_acc = 91.00% in 1011
[INFO: 2021-08-06 03:20:47,873] Current checkpoints:
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-4.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-5.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-6.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-7.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-8.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-9.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-10.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-3.pth.tar', 0.8140454995054401)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-2.pth.tar', 0.8031651829871415)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-1.pth.tar', 0.7833827893175074)

[INFO: 2021-08-06 03:20:57,835] Distributing BatchNorm running means and vars
[INFO: 2021-08-06 03:21:19,902] Epoch: 11, top1_acc = 81.50%, top5_acc = 90.60% in 1011
[INFO: 2021-08-06 03:21:42,415] Epoch: 11, top1_acc = 81.50%, top5_acc = 91.00% in 1011
[INFO: 2021-08-06 03:21:46,052] Cleaning checkpoint: ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-1.pth.tar', 0.7833827893175074)
[INFO: 2021-08-06 03:21:46,121] Current checkpoints:
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-4.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-5.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-6.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-7.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-8.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-9.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-10.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-11.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-3.pth.tar', 0.8140454995054401)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-2.pth.tar', 0.8031651829871415)

[INFO: 2021-08-06 03:21:57,140] Distributing BatchNorm running means and vars
[INFO: 2021-08-06 03:22:19,407] Epoch: 12, top1_acc = 81.50%, top5_acc = 98.12% in 1011
[INFO: 2021-08-06 03:22:43,320] Epoch: 12, top1_acc = 81.50%, top5_acc = 91.00% in 1011
[INFO: 2021-08-06 03:22:46,589] Cleaning checkpoint: ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-2.pth.tar', 0.8031651829871415)
[INFO: 2021-08-06 03:22:46,671] Current checkpoints:
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-4.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-5.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-6.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-7.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-8.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-9.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-10.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-11.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-12.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-3.pth.tar', 0.8140454995054401)

[INFO: 2021-08-06 03:22:58,515] Distributing BatchNorm running means and vars
[INFO: 2021-08-06 03:23:20,010] Epoch: 13, top1_acc = 81.50%, top5_acc = 97.73% in 1011
[INFO: 2021-08-06 03:23:41,497] Epoch: 13, top1_acc = 81.50%, top5_acc = 91.00% in 1011
[INFO: 2021-08-06 03:23:45,675] Cleaning checkpoint: ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-3.pth.tar', 0.8140454995054401)
[INFO: 2021-08-06 03:23:45,767] Current checkpoints:
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-4.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-5.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-6.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-7.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-8.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-9.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-10.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-11.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-12.pth.tar', 0.8150346191889218)
 ('./cot_experiments/CoTNet_SYS/snapshot/checkpoint-13.pth.tar', 0.8150346191889218)

[INFO: 2021-08-06 03:23:56,316] Distributing BatchNorm running means and vars
[INFO: 2021-08-06 03:24:18,093] Epoch: 14, top1_acc = 81.50%, top5_acc = 97.82% in 1011
[INFO: 2021-08-06 03:24:39,590] Epoch: 14, top1_acc = 81.50%, top5_acc = 91.00% in 1011
[INFO: 2021-08-06 03:24:53,347] Distributing BatchNorm running means and vars
[INFO: 2021-08-06 03:25:14,962] Epoch: 15, top1_acc = 81.50%, top5_acc = 98.42% in 1011
[INFO: 2021-08-06 03:25:35,680] Epoch: 15, top1_acc = 81.50%, top5_acc = 91.00% in 1011
[INFO: 2021-08-06 03:25:51,451] Distributing BatchNorm running means and vars
[INFO: 2021-08-06 03:26:13,676] Epoch: 16, top1_acc = 81.50%, top5_acc = 98.22% in 1011
[INFO: 2021-08-06 03:26:35,126] Epoch: 16, top1_acc = 81.50%, top5_acc = 91.00% in 1011
[INFO: 2021-08-06 03:26:50,542] Distributing BatchNorm running means and vars
[INFO: 2021-08-06 03:27:11,586] Epoch: 17, top1_acc = 81.50%, top5_acc = 98.32% in 1011
[INFO: 2021-08-06 03:27:33,794] Epoch: 17, top1_acc = 81.50%, top5_acc = 91.00% in 1011
[INFO: 2021-08-06 03:27:49,459] Distributing BatchNorm running means and vars
[INFO: 2021-08-06 03:28:10,617] Epoch: 18, top1_acc = 81.50%, top5_acc = 98.22% in 1011
[INFO: 2021-08-06 03:28:33,301] Epoch: 18, top1_acc = 81.50%, top5_acc = 91.00% in 1011
[INFO: 2021-08-06 03:28:49,734] Distributing BatchNorm running means and vars
[INFO: 2021-08-06 03:29:13,685] Epoch: 19, top1_acc = 81.50%, top5_acc = 97.92% in 1011
[INFO: 2021-08-06 03:29:37,327] Epoch: 19, top1_acc = 81.50%, top5_acc = 91.00% in 1011
[INFO: 2021-08-06 03:29:51,919] Distributing BatchNorm running means and vars
[INFO: 2021-08-06 03:30:14,903] Epoch: 20, top1_acc = 81.50%, top5_acc = 98.32% in 1011

**Comment by ai1361720220000** [comment]
另外请问下，torchvision版本是多少呢

**Comment by YehLi** [comment]
If the dataset is small, the performance will get saturated in a few epochs.  My torchvision is 0.10.0+cu102

**Comment by ai1361720220000** [comment]
> If the dataset is small, the performance will get saturated in a few epochs. My torchvision is 0.10.0+cu102

我调整了数据集规模，下面是我的训练结果，可以看到每次模型会输出两个eval结果，第一个都会比第二个高，从train.py中看出第二个eval是和model_ema有关，请问model_ema是什么用处的呢？第一个model结果要高很多，为什么要保存model_ema的权重呢？
那在测试阶段，我需要用model读取权重呢？还是用model_ema读取权重呢？

**Comment by YehLi** [comment]
Exponential moving average(EMA) is mainly used to stabilize the training. model_ema usually achieves better result after about 30 epochs. In your case, you need to modify the model_ema_decay parameter to make EMA work, since your model converge just in a few epochs.

**Comment by ai1361720220000** [comment]
我需要调小这个参数吗？我不是很清楚如何调整这个参数。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: YehLi ***@***.***&gt;
发送时间: 2021年8月7日 18:52
收件人: JDAI-CV/CoTNet ***@***.***&gt;
抄送: Alxendx ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[JDAI-CV/CoTNet] 训练精度提不上去 (#9)





 
Exponential moving average(EMA) is mainly used to stabilize the training. model_ema usually achieves better result after about 30 epochs. In your case, you need to modify the model_ema_decay parameter to make EMA work, since your model converge just in a few epochs.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YehLi** [comment]
You can set the model_ema_decay smaller, e.g., 0.99 or 0.999. I think you can train the model without ema since your model has already achieved high top-1 accuracy.

**Comment by ai1361720220000** [comment]
非常感谢你对我的耐心回答～感谢～我之后去试一试。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: YehLi ***@***.***&gt;
发送时间: 2021年8月7日 20:28
收件人: JDAI-CV/CoTNet ***@***.***&gt;
抄送: Alxendx ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[JDAI-CV/CoTNet] 训练精度提不上去 (#9)





 
You can set the model_ema_decay smaller, e.g., 0.99 or 0.999. I think you can train the model without ema since your model has already achieved high top-1 accuracy.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
